dataset:
  train:
    # Peptides
    - class: DynamicBatchWrapper
      dataset:
        class: MixDatasetWrapper
        datasets:
          # pepbench
          - class: PeptideDataset
            mmap_dir: ./datasets/peptide/pepbench/processed
            specify_index: ./datasets/peptide/pepbench/processed/train_index.txt
            cluster: ./datasets/peptide/pepbench/train.cluster
            length_type: block
          # protein-peptide complex with non standard amino acids
          - class: PeptideDataset
            mmap_dir: ./datasets/peptide/pepbench/processed
            specify_index: ./datasets/peptide/pepbench/processed/non_standard_index.txt
            length_type: block
          # protein-fragments
          - class: PeptideDataset
            mmap_dir: ./datasets/peptide/ProtFrag/processed
            length_type: block
        # weights: [1.0, 1.0, 1.0]
      complexity: n*n
      ubound_per_batch: 180000  # reduce from 1800000
      n_use_max_in_batch: true
    # Small Molecules
    - class: DynamicBatchWrapper
      dataset: # crossdocked
        class: MoleculeDataset
        mmap_dir: ./datasets/molecule/CrossDocked/processed
        specify_index: ./datasets/molecule/CrossDocked/processed/train_index.txt
        length_type: block
      complexity: n*n
      ubound_per_batch: 80000  # reduce from 800000
      n_use_max_in_batch: true
    # Antibody
    - class: DynamicBatchWrapper
      dataset:
        class: AntibodyDataset
        mmap_dir: ./datasets/antibody/SAbDab/processed
        specify_index: ./datasets/antibody/SAbDab/processed/train_index.txt
        length_type: block
      complexity: n*n
      ubound_per_batch: 90000  # reduce from 900000
      n_use_max_in_batch: true
  valid:
    - class: DynamicBatchWrapper
      dataset: 
        class: PeptideDataset
        mmap_dir: ./datasets/peptide/pepbench/processed
        specify_index: ./datasets/peptide/pepbench/processed/valid_index.txt
        length_type: block
      complexity: n*n
      ubound_per_batch: 180000  # reduce from 1800000
      n_use_max_in_batch: true
    - class: DynamicBatchWrapper
      dataset: 
        class: MoleculeDataset
        mmap_dir: ./datasets/molecule/CrossDocked/processed
        specify_index: ./datasets/molecule/CrossDocked/processed/valid_index.txt
        length_type: block
      complexity: n*n
      ubound_per_batch: 60000 # reduced from 600000 # avoid autoencoder OOM in validation
      n_use_max_in_batch: true
    - class: DynamicBatchWrapper
      dataset: 
        class: AntibodyDataset
        mmap_dir: ./datasets/antibody/SAbDab/processed
        specify_index: ./datasets/antibody/SAbDab/processed/valid_index.txt
        length_type: block
      complexity: n*n
      ubound_per_batch: 90000  # reduce from 900000
      n_use_max_in_batch: true

dataloader:
  train:
    shuffle: true
    num_workers: 4 #16
  valid:
    num_workers: 2 #8

trainer:
  class: RectTrainer  # Changed from LDMTrainer
  criterion: total    # Changed from loss to total
  config:
    max_epoch: 20
    save_topk: 10
    val_freq: 1
    save_dir: ./ckpts/unimomo
    patience: 10
    metric_min_better: true
    proj_name: UniMoMo-Flow # for wandb
    logger: tensorboard # if you want to use wandb, please comment this line 

    optimizer:
      class: AdamW
      lr: 1.0e-4

    scheduler:
      class: ReduceLROnPlateau
      factor: 0.8
      patience: 5
      mode: min
      frequency: val_epoch
      min_lr: 5.0e-6

model:
  class: RectifiedFlowMolDesign  # Changed from LDMMolDesign
  autoencoder_ckpt: '' # load by yourself
  latent_deterministic: true  # without resample in training
  hidden_size: 512
  h_loss_weight: 1.0
  std: 10.0
  flow_opt:  # Replaced diffusion_opt with flow_opt
    encoder_type: EPT
    encoder_opt:
      n_layers: 6
      n_rbf: 16
      cutoff: 7.0
    sigma: 1.0e-4  # Conditional flow matching noise level
  is_aa_corrupt_ratio: 0.1

load_ckpt: ''